const eventsData = [
{
	"id": "18",
	"tipo": "Curso",
	"entidad": "Facultad de Derecho",
	"sede": "Palacio de Autonomía",
	"id_curso": "17",
	"curso": "Comunicación Estratégica en Situaciones de Crisis",
	"modalidad": "En línea",
	"duracion": "20",
	"cuota": "4000.00",
	"fecha_inicio": "2022-05-12",
	"link": "https://fb.me/e/4tLD9IluK",
	"imagen": "cursos/Derecho_Crisis.png"
}, {
	"id": "19",
	"tipo": "Curso",
	"entidad": "Facultad de Derecho",
	"sede": "Palacio de Autonomía",
	"id_curso": "15",
	"curso": "Imagen Profesional Eficaz Para Abogados",
	"modalidad": "En línea",
	"duracion": "20",
	"cuota": "4000.00",
	"fecha_inicio": "2022-04-30",
	"link": "https://fb.me/e/2uAA8e34K",
	"imagen": "cursos/Derecho_Imagen (1).png"
}, {
	"id": "20",
	"tipo": "Curso",
	"entidad": "Facultad de Derecho",
	"sede": "Palacio de Autonomía",
	"id_curso": "10",
	"curso": "Estrategia de Comunicaciones en Redes Sociales",
	"modalidad": "En línea",
	"duracion": "40",
	"cuota": "4000.00",
	"fecha_inicio": "2022-04-03",
	"link": "https://fb.me/e/1c4rNWxTf",
	"imagen": "cursos/ECRS_Abril.png"
}, {
	"id": "21",
	"tipo": "Curso",
	"entidad": "Facultad de Derecho",
	"sede": "Palacio de Autonomía",
	"id_curso": "23",
	"curso": "Promoción Estratégica de Negocios en Tiempo de Crisis",
	"modalidad": "En línea",
	"duracion": "40",
	"cuota": "4000.00",
	"fecha_inicio": "2022-05-22",
	"link": "https://fb.me/e/1KZqEKocw",
	"imagen": "cursos/Derecho_Promoción.png"
}, {
	"id": "22",
	"tipo": "Curso",
	"entidad": "Facultad de Filosofía y Letras",
	"sede": "Tlalpan",
	"id_curso": "106",
	"curso": "Nueve cuentistas mexicanas 2 ",
	"modalidad": "En línea",
	"duracion": "20",
	"cuota": "2988.00",
	"fecha_inicio": "2022-03-03",
	"link": "http://ec.filos.unam.mx/2021/12/03/nueve-cuentistas-mexicanas-2-2/",
	"imagen": "cursos/NUEVE CUENTISTAS CONFIRMADO.jpg"
}, {
	"id": "23",
	"tipo": "Curso",
	"entidad": "Facultad de Filosofía y Letras",
	"sede": "Tlalpan",
	"id_curso": "18",
	"curso": "Crónica Periodística: Teoría y Práctica",
	"modalidad": "En línea",
	"duracion": "30",
	"cuota": "4700.00",
	"fecha_inicio": "2022-04-22",
	"link": "http://ec.filos.unam.mx/cronica-periodistica-teoria-y-practica/",
	"imagen": "cursos/cronica confirmado.png"
}, {
	"id": "24",
	"tipo": "Curso",
	"entidad": "Facultad de Filosofía y Letras",
	"sede": "Tlalpan",
	"id_curso": "9",
	"curso": "Redacción y corrección de textos profesionales",
	"modalidad": "En línea",
	"duracion": "40",
	"cuota": "6200.00",
	"fecha_inicio": "2022-02-04",
	"link": "http://ec.filos.unam.mx/2020/09/22/redaccion-y-correccion-de-textos-profesionales/",
	"imagen": "cursos/Redacción y corrección de textos (6).jpg"
}, {
	"id": "26",
	"tipo": "Curso",
	"entidad": "Facultad de Ciencias",
	"sede": "Tlalpan",
	"id_curso": "6",
	"curso": "Introducción a la programación en R y su aplicación a la inferencia estadística, módulo I",
	"modalidad": "En línea",
	"duracion": "40",
	"cuota": "5000.00",
	"fecha_inicio": "2022-03-31",
	"link": "http://www.educontinua.fciencias.unam.mx/SiteNuevo/Cursos/R/2022/Intro.php",
	"imagen": "cursos/R1 confirmado.png"
}, {
	"id": "27",
	"tipo": "Curso",
	"entidad": "Facultad de Ciencias",
	"sede": "Tlalpan",
	"id_curso": "20",
	"curso": "Excel: Uso y Aplicaciones",
	"modalidad": "En línea",
	"duracion": "21",
	"cuota": "2700.00",
	"fecha_inicio": "2022-05-04",
	"link": "http://www.educontinua.fciencias.unam.mx/SiteNuevo/Cursos/Excel/2022/II/Intro.php",
	"imagen": "cursos/WhatsApp Image 2022-04-27 at 12.21.13 PM.jpeg"
}, {
	"id": "29",
	"tipo": "Curso",
	"entidad": "FES Iztacala",
	"sede": "Palacio de Autonomía",
	"id_curso": "31",
	"curso": "El Arte del Coaching en El ámbito Educativo",
	"modalidad": "En línea",
	"duracion": "40",
	"cuota": "3350.00",
	"fecha_inicio": "2022-05-17",
	"link": "https://deunam.iztacala.unam.mx/index.php/educacion-continua-oferta-academica/cursos-inscripciones-e-informes/item/el-arte-del-coaching-en-el-ambito-educativo-2",
	"imagen": "cursos/FESI_ACAE.png"
}, {
	"id": "30",
	"tipo": "Curso",
	"entidad": "FES Iztacala",
	"sede": "Palacio de Autonomía",
	"id_curso": "8",
	"curso": "El Arte de Hablar en Público",
	"modalidad": "En línea",
	"duracion": "24",
	"cuota": "2250.00",
	"fecha_inicio": "2022-04-30",
	"link": "https://deunam.iztacala.unam.mx/index.php/educacion-continua-oferta-academica/cursos-inscripciones-e-informes/item/taller",
	"imagen": "cursos/FESI_HEP.png"
}, {
	"id": "31",
	"tipo": "Curso",
	"entidad": "FES Iztacala",
	"sede": "Palacio de Autonomía",
	"id_curso": "30",
	"curso": "El Amor Romántico y la Violencia de Género",
	"modalidad": "En línea",
	"duracion": "10",
	"cuota": "1800.00",
	"fecha_inicio": "2022-09-05",
	"link": "https://deunam.iztacala.unam.mx/index.php/educacion-continua-oferta-academica/cursos-inscripciones-e-informes/item/ct-amor-romantico",
	"imagen": "cursos/el amor romantico twiter.jpg"
}, {
	"id": "33",
	"tipo": "Curso",
	"entidad": "FES Iztacala",
	"sede": "Palacio de Autonomía",
	"id_curso": "32",
	"curso": "Fortalecer Mi Autoestima y Mis Emociones",
	"modalidad": "En línea",
	"duracion": "20",
	"cuota": "2250.00",
	"fecha_inicio": "2022-05-12",
	"link": "https://deunam.iztacala.unam.mx/index.php/educacion-continua-oferta-academica/cursos-inscripciones-e-informes/item/taller-fortaleciendo-mi-autoestima-y-mis-emociones?fbclid=IwAR30-wei-BgriQcO05ZxjrPZAoVKxHWt_2TAlP0Fn1NFt58CnOxpS8r4Pk0",
	"imagen": "cursos/FESI_FAE.png"
}, {
	"id": "37",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "27",
	"curso": "Tradiciones y Cultura Mexicana",
	"modalidad": "En línea",
	"duracion": "50",
	"cuota": "4000.00",
	"fecha_inicio": "2022-05-02",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/2332",
	"imagen": "cursos/Aragon_Tradiciones.png"
}, {
	"id": "38",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "24",
	"curso": "Historia Mínima de México",
	"modalidad": "En línea",
	"duracion": "60",
	"cuota": "4500.00",
	"fecha_inicio": "2022-05-02",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/2302",
	"imagen": "cursos/Aragon_HistoriaMM.png"
}, {
	"id": "40",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "22",
	"curso": "Excel Ejecutivo Básico-Intermedio-Avanzado",
	"modalidad": "Semipresencial",
	"duracion": "60",
	"cuota": "4400.00",
	"fecha_inicio": "2022-07-09",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/3105",
	"imagen": "cursos/Aragon_MEEBIA (1).png"
}, {
	"id": "41",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "19",
	"curso": "Curso Introducción a la Calidad y 5S",
	"modalidad": "A distancia",
	"duracion": "20",
	"cuota": "1500.00",
	"fecha_inicio": "2022-02-28",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/2615",
	"imagen": "cursos/5 s.jpg"
}, {
	"id": "48",
	"tipo": "Curso",
	"entidad": "Facultad de Ciencias",
	"sede": "Tlalpan",
	"id_curso": "13",
	"curso": "Introducción a la programación en R y su aplicación a la inferencia estadística módulo II",
	"modalidad": "En línea",
	"duracion": "40",
	"cuota": "5000.00",
	"fecha_inicio": "2022-03-12",
	"link": "http://www.educontinua.fciencias.unam.mx/SiteNuevo/Cursos/RII/2022/Intro.php",
	"imagen": "cursos/Ciencias_RII.png"
}, {
	"id": "49",
	"tipo": "Curso",
	"entidad": "Facultad de Ciencias",
	"sede": "Tlalpan",
	"id_curso": "90",
	"curso": "Introducción a la divulgación de la ciencia",
	"modalidad": "En línea",
	"duracion": "20",
	"cuota": "2600.00",
	"fecha_inicio": "2022-04-29",
	"link": "https://educontinua.fciencias.unam.mx/SiteNuevo/Cursos/DivulgacionCiencia/2022/Intro.php",
	"imagen": "cursos/divulgación de la ciencia confirmado.jpg"
}, {
	"id": "50",
	"tipo": "Curso",
	"entidad": "Facultad de Ciencias",
	"sede": "Tlalpan",
	"id_curso": "5",
	"curso": "Estadística Descriptiva en Línea",
	"modalidad": "En línea",
	"duracion": "20",
	"cuota": "2500.00",
	"fecha_inicio": "2022-05-17",
	"link": "http://www.educontinua.fciencias.unam.mx/SiteNuevo/Cursos/EstadisticaDescriptiva/2022/II/Intro.php",
	"imagen": "cursos/Ciencias_Estadística.png"
}, {
	"id": "51",
	"tipo": "Curso",
	"entidad": "Facultad de Filosofía y Letras",
	"sede": "Tlalpan",
	"id_curso": "101",
	"curso": "Alimentación y modernidad en la cultura culinaria mexicana",
	"modalidad": "En línea",
	"duracion": "22",
	"cuota": "3294.00",
	"fecha_inicio": "2022-06-20",
	"link": "http://ec.filos.unam.mx/alimentacion-y-modernidad-en-la-cultura-culinaria-mexicana/",
	"imagen": "cursos/Alimentación y modernidad en la cultura culinaria mexicana.jpg"
}, {
	"id": "52",
	"tipo": "Curso",
	"entidad": "Facultad de Filosofía y Letras",
	"sede": "Tlalpan",
	"id_curso": "102",
	"curso": "Análisis de escritores de divulgación de la ciencia",
	"modalidad": "En línea",
	"duracion": "30",
	"cuota": "4700.00",
	"fecha_inicio": "2022-05-24",
	"link": "http://ec.filos.unam.mx/analisis-de-escritores-de-divulgacion-de-la-ciencia/",
	"imagen": "cursos/FFyL_Ciencia.png"
}, {
	"id": "53",
	"tipo": "Curso",
	"entidad": "Facultad de Filosofía y Letras",
	"sede": "Tlalpan",
	"id_curso": "103",
	"curso": "Taller de Novela",
	"modalidad": "En línea",
	"duracion": "30",
	"cuota": "4700.00",
	"fecha_inicio": "2022-05-04",
	"link": "http://ec.filos.unam.mx/taller-de-novela/",
	"imagen": "cursos/novela confirmado.png"
}, {
	"id": "54",
	"tipo": "Curso",
	"entidad": "Facultad de Filosofía y Letras",
	"sede": "Tlalpan",
	"id_curso": "104",
	"curso": "Enfermar y curar en el México Virreinal: un acercamiento a las prácticas corporales",
	"modalidad": "En línea",
	"duracion": "20",
	"cuota": "2988.00",
	"fecha_inicio": "2022-05-30",
	"link": "http://ec.filos.unam.mx/2021/12/03/enfermar-y-curar-en-el-mexico-virreinal-un-acercamiento-a-las-practicas-corporales/",
	"imagen": "cursos/Enfermar y curar en el México Virreinal.webp"
}, {
	"id": "55",
	"tipo": "Curso",
	"entidad": "FES Iztacala",
	"sede": "Palacio de Autonomía",
	"id_curso": "105",
	"curso": "Innovación y emprendimiento",
	"modalidad": "En línea",
	"duracion": "25",
	"cuota": "2500.00",
	"fecha_inicio": "2022-04-30",
	"link": "https://deunam.iztacala.unam.mx/index.php/psicologia/item/innovacion-y-emprendimiento",
	"imagen": "cursos/inovación.jpg"
}, {
	"id": "62",
	"tipo": "Curso",
	"entidad": "FES Iztacala",
	"sede": "Palacio de Autonomía",
	"id_curso": "12",
	"curso": "Manejo de Residuos Peligrosos Biológico-Infecciosos",
	"modalidad": "En línea",
	"duracion": "20",
	"cuota": "2400.00",
	"fecha_inicio": "2022-06-02",
	"link": "https://deunam.iztacala.unam.mx/index.php/educacion-continua-oferta-academica/cursos-inscripciones-e-informes/item/manejo-de-residuos-peligrosos-biologico-infecciosos",
	"imagen": "cursos/FESI_Residuos.png"
}, {
	"id": "64",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "110",
	"curso": "Comunicación e Identidad Organizacional",
	"modalidad": "A distancia",
	"duracion": "24",
	"cuota": "3000.00",
	"fecha_inicio": "2022-03-25",
	"link": "https://www.acatlan.unam.mx/index.php?id=284",
	"imagen": "cursos/E CIO.png"
}, {
	"id": "65",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "109",
	"curso": "Investigación de mercados",
	"modalidad": "A distancia",
	"duracion": "20",
	"cuota": "2500.00",
	"fecha_inicio": "2022-05-07",
	"link": "https://www.acatlan.unam.mx/index.php?id=1430",
	"imagen": "cursos/E IDM.png"
}, {
	"id": "66",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "49",
	"curso": "Excel Básico",
	"modalidad": "A distancia",
	"duracion": "20",
	"cuota": "1670.00",
	"fecha_inicio": "2022-02-26",
	"link": "https://www.acatlan.unam.mx/index.php?id=289",
	"imagen": "cursos/E ExcelBásico.png"
}, {
	"id": "67",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "108",
	"curso": "Excel Intermedio",
	"modalidad": "A distancia",
	"duracion": "20",
	"cuota": "1740.00",
	"fecha_inicio": "2022-04-02",
	"link": "https://www.acatlan.unam.mx/index.php?id=1204",
	"imagen": "cursos/E ExcelIntermedio.png"
}, {
	"id": "70",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "112",
	"curso": "Visión Teórico Práctica del Juicio de Amparo en Materia Penal",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-05-20",
	"link": "https://www.acatlan.unam.mx/index.php?id=1043",
	"imagen": "cursos/E VTP.png"
}, {
	"id": "82",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "65",
	"curso": "Pedagogía del arte",
	"modalidad": "A distancia",
	"duracion": "36",
	"cuota": "2700.00",
	"fecha_inicio": "2022-01-08",
	"link": "https://www.facebook.com/events/482777216346466/",
	"imagen": "cursos/FESA_PA.png"
}, {
	"id": "88",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "119",
	"curso": "Flash CS5 ",
	"modalidad": "Semipresencial",
	"duracion": "20",
	"cuota": "2000.00",
	"fecha_inicio": "2022-02-23",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/2598",
	"imagen": "cursos/Flash CS5.jpg"
}, {
	"id": "89",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "120",
	"curso": "Solidworks",
	"modalidad": "Presencial",
	"duracion": "20",
	"cuota": "2000.00",
	"fecha_inicio": "2022-02-22",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/2595",
	"imagen": "cursos/Solid Works.jpg"
}, {
	"id": "90",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "121",
	"curso": "Autocad 2D",
	"modalidad": "Presencial",
	"duracion": "20",
	"cuota": "2000.00",
	"fecha_inicio": "2022-02-21",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/2596",
	"imagen": "cursos/Autocad 2D.JPG"
}, {
	"id": "91",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "122",
	"curso": "Inglés, Comprensión de Lectura - 1º nivel ",
	"modalidad": "Presencial",
	"duracion": "72",
	"cuota": "4100.00",
	"fecha_inicio": "2022-03-22",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/2738",
	"imagen": "cursos/inglés L-V.JPG"
}, {
	"id": "94",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "123",
	"curso": "Fotografía para todos",
	"modalidad": "A distancia",
	"duracion": "24",
	"cuota": "3000.00",
	"fecha_inicio": "2022-02-08",
	"link": "https://www.acatlan.unam.mx/index.php?id=332",
	"imagen": "cursos/E FPT.png"
}, {
	"id": "96",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "125",
	"curso": "Storytelling",
	"modalidad": "A distancia",
	"duracion": "30",
	"cuota": "3750.00",
	"fecha_inicio": "2022-02-12",
	"link": "https://www.acatlan.unam.mx/index.php?id=1305",
	"imagen": "cursos/E Story.png"
}, {
	"id": "97",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "64",
	"curso": "Coaching y Equipos de Trabajo",
	"modalidad": "A distancia",
	"duracion": "32",
	"cuota": "4000.00",
	"fecha_inicio": "2022-02-25",
	"link": "https://www.acatlan.unam.mx/index.php?id=1046",
	"imagen": "cursos/E Coaching.png"
}, {
	"id": "99",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "127",
	"curso": "Comunicación y servicio al cliente interno",
	"modalidad": "A distancia",
	"duracion": "20",
	"cuota": "4000.00",
	"fecha_inicio": "2022-04-23",
	"link": "https://www.acatlan.unam.mx/index.php?id=1203",
	"imagen": "cursos/E Clienteinterno.png"
}, {
	"id": "100",
	"tipo": "Curso",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "128",
	"curso": "Excel Avanzado",
	"modalidad": "A distancia",
	"duracion": "20",
	"cuota": "1800.00",
	"fecha_inicio": "2022-05-07",
	"link": "https://www.acatlan.unam.mx/index.php?id=645",
	"imagen": "cursos/E ExcelAvanzado.png"
}, {
	"id": "115",
	"tipo": "Curso",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "134",
	"curso": "Bases para el desarrollo de la etapa de juicio oral penal",
	"modalidad": "Presencial",
	"duracion": "20",
	"cuota": "1500.00",
	"fecha_inicio": "2022-06-04",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/3137",
	"imagen": "cursos/WhatsApp Image 2022-04-27 at 12.11.14 PM.jpeg"
}, {
	"id": "95",
	"tipo": "Taller",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "124",
	"curso": "Fábrica de contenidos digitales",
	"modalidad": "A distancia",
	"duracion": "10",
	"cuota": "1250.00",
	"fecha_inicio": "2022-02-12",
	"link": "https://www.acatlan.unam.mx/index.php?id=1227",
	"imagen": "cursos/E Fabrica.png"
}, {
	"id": "98",
	"tipo": "Taller",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "126",
	"curso": "InstaPlanning: Tu estrategia publicitaria en 10 horas",
	"modalidad": "A distancia",
	"duracion": "10",
	"cuota": "1250.00",
	"fecha_inicio": "2022-03-26",
	"link": "https://www.acatlan.unam.mx/index.php?id=1228",
	"imagen": "cursos/E Instaplanning.png"
}, {
	"id": "1",
	"tipo": "Diplomado",
	"entidad": "FES Iztacala",
	"sede": "Tlalpan",
	"id_curso": "42",
	"curso": "La Prueba Pericial en el Proceso Penal Acusatorio",
	"modalidad": "En línea",
	"duracion": "195",
	"cuota": "20400.00",
	"fecha_inicio": "2022-02-25",
	"link": "https://deunam.iztacala.unam.mx/index.php/abogados/item/prueba-pericial",
	"imagen": "cursos/FESI_PPPPA.png"
}, {
	"id": "2",
	"tipo": "Diplomado",
	"entidad": "FES Iztacala",
	"sede": "Tlalpan",
	"id_curso": "39",
	"curso": "Herramientas y Habilidades Psicopedagógicas para el Docente del Siglo XXI",
	"modalidad": "En línea",
	"duracion": "120",
	"cuota": "15550.00",
	"fecha_inicio": "2022-03-15",
	"link": "https://deunam.iztacala.unam.mx/index.php/pedagogos/item/siglo-xxi?fbclid=IwAR3yAyumnfFAceLsFmHTgKGQEeDpDqyqKuHWTGeWRw1AsvolI25ZrxQez_U",
	"imagen": "cursos/FESI_HPXXI.png"
}, {
	"id": "3",
	"tipo": "Diplomado",
	"entidad": "FES Iztacala",
	"sede": "Palacio de Autonomía",
	"id_curso": "35",
	"curso": "Auditoría Forense e Incidentes Cibernéticos",
	"modalidad": "En línea",
	"duracion": "190",
	"cuota": "24700.00",
	"fecha_inicio": "2022-10-01",
	"link": "https://deunam.iztacala.unam.mx/index.php/abogados/item/auditoria-forense-2?fbclid=IwAR2bHIO5Br-8HKZRk3JJgP0_ZxcO2yUxdP1OsSe2lqBzaWm6iMFtmNn45S0",
	"imagen": "cursos/FESI_AFIC.png"
}, {
	"id": "4",
	"tipo": "Diplomado",
	"entidad": "FES Zaragoza",
	"sede": "Tlalpan",
	"id_curso": "46",
	"curso": "Sistema de Gestión de la Calidad ISO 9001:2015. Interpretación, Implementación, Auditoría y Certificación.",
	"modalidad": "En línea",
	"duracion": "150",
	"cuota": "17000.00",
	"fecha_inicio": "2022-08-11",
	"link": "https://fb.me/e/2JsPnW2JQ",
	"imagen": "cursos/Zaragoza_9001.png"
}, {
	"id": "5",
	"tipo": "Diplomado",
	"entidad": "FES Zaragoza",
	"sede": "Tlalpan",
	"id_curso": "45",
	"curso": "Sistema de Gestión Ambiental ISO 14001:2015. Interpretación, Implantación y Auditoría.",
	"modalidad": "En línea",
	"duracion": "150",
	"cuota": "17000.00",
	"fecha_inicio": "2022-08-11",
	"link": "https://fb.me/e/10AFp89Ue",
	"imagen": "cursos/Zaragoza_14001.png"
}, {
	"id": "6",
	"tipo": "Diplomado",
	"entidad": "FES Zaragoza",
	"sede": "Tlalpan",
	"id_curso": "48",
	"curso": "Sistema de Gestión de la Seguridad y Salud en El Trabajo ISO 45001:2018. Interpretación, Implantación y Auditoría.",
	"modalidad": "En línea",
	"duracion": "150",
	"cuota": "17000.00",
	"fecha_inicio": "2022-08-11",
	"link": "https://fb.me/e/4bbieenbR",
	"imagen": "cursos/Zaragoza_45001.png"
}, {
	"id": "7",
	"tipo": "Diplomado",
	"entidad": "FES Zaragoza",
	"sede": "Tlalpan",
	"id_curso": "47",
	"curso": "Sistema de Gestión de la Energía ISO 50001:2011. Interpretación, Implantación y Auditoría.",
	"modalidad": "En línea",
	"duracion": "150",
	"cuota": "17000.00",
	"fecha_inicio": "2022-08-11",
	"link": "https://fb.me/e/MDZuJnUl",
	"imagen": "cursos/Zaragoza_50001.png"
}, {
	"id": "8",
	"tipo": "Diplomado",
	"entidad": "FES Zaragoza",
	"sede": "Tlalpan",
	"id_curso": "41",
	"curso": "Integración de Sistemas de Gestión ISO 9001:2015, ISO 14001:2015 e ISO 45001:2018",
	"modalidad": "En línea",
	"duracion": "240",
	"cuota": "22000.00",
	"fecha_inicio": "2022-08-11",
	"link": "https://fb.me/e/12fLgTP0c",
	"imagen": "cursos/Zaragoza_Integración.png"
}, {
	"id": "9",
	"tipo": "Diplomado",
	"entidad": "FES Zaragoza",
	"sede": "Tlalpan",
	"id_curso": "38",
	"curso": "Gestión Integral de Residuos",
	"modalidad": "En línea",
	"duracion": "240",
	"cuota": "22000.00",
	"fecha_inicio": "2022-08-11",
	"link": "https://fb.me/e/19wgBved7",
	"imagen": "cursos/Zaragoza_Residuos.png"
}, {
	"id": "10",
	"tipo": "Diplomado",
	"entidad": "FES Zaragoza",
	"sede": "Tlalpan",
	"id_curso": "44",
	"curso": "Selección, Operación y Mantenimiento de Sistemas de Tratamiento de Agua Residual",
	"modalidad": "En línea",
	"duracion": "240",
	"cuota": "22000.00",
	"fecha_inicio": "2022-08-11",
	"link": "https://fb.me/e/5ZYgzKDbz",
	"imagen": "cursos/Zaragoza_Aguas.png"
}, {
	"id": "11",
	"tipo": "Diplomado",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "40",
	"curso": "Instructor de Yoga",
	"modalidad": "Presencial",
	"duracion": "156",
	"cuota": "15000.00",
	"fecha_inicio": "2022-05-14",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/2972",
	"imagen": "cursos/Yoga.jpg"
}, {
	"id": "13",
	"tipo": "Diplomado",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "107",
	"curso": "Estimulación Temprana ",
	"modalidad": "En línea",
	"duracion": "120",
	"cuota": "9000.00",
	"fecha_inicio": "2022-02-05",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/2975",
	"imagen": "cursos/Aragon_DET (1).png"
}, {
	"id": "42",
	"tipo": "Diplomado",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "43",
	"curso": "Recursos Digitales para la Educación",
	"modalidad": "En línea",
	"duracion": "240",
	"cuota": "16500.00",
	"fecha_inicio": "2022-05-14",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/3106",
	"imagen": "cursos/recursos.jpg"
}, {
	"id": "68",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "111",
	"curso": "Control y Transparencia en la Administración Pública",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-01-08",
	"link": "https://www.acatlan.unam.mx/index.php?id=1431",
	"imagen": "cursos/FESA_CTAP.png"
}, {
	"id": "71",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "53",
	"curso": "Sistema Nacional Anticorrupción: Servidores públicos y empresas",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-05-24",
	"link": "https://www.acatlan.unam.mx/index.php?id=857",
	"imagen": "cursos/E SNA.png"
}, {
	"id": "72",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "67",
	"curso": "Derecho penal y Dogmática penal contemporánea",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-06-25",
	"link": "https://www.acatlan.unam.mx/index.php?id=1372",
	"imagen": "cursos/E DPDPC.png"
}, {
	"id": "73",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "114",
	"curso": "Derecho familiar",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-05-20",
	"link": "https://www.acatlan.unam.mx/index.php?id=415",
	"imagen": "cursos/E Familiar.png"
}, {
	"id": "74",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "115",
	"curso": "Aspectos legales aplicables al comercio exterior",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-03-19",
	"link": "https://www.acatlan.unam.mx/index.php?id=368",
	"imagen": "cursos/E ALACE.png"
}, {
	"id": "75",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "117",
	"curso": "Derecho empresarial",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-03-20",
	"link": "https://www.acatlan.unam.mx/index.php?id=1207",
	"imagen": "cursos/E DE.png"
}, {
	"id": "76",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "54",
	"curso": "Derecho procesal electoral",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-04-23",
	"link": "https://www.acatlan.unam.mx/index.php?id=1410",
	"imagen": "cursos/E DPE.png"
}, {
	"id": "77",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "55",
	"curso": "Derecho procesal penal",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-04-22",
	"link": "https://www.acatlan.unam.mx/index.php?id=1366",
	"imagen": "cursos/E DPP.png"
}, {
	"id": "78",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "87",
	"curso": "Organización, Comunicación y Cultura - Seminario Taller Extracurricular ",
	"modalidad": "A distancia",
	"duracion": "200",
	"cuota": "13200.00",
	"fecha_inicio": "2022-04-23",
	"link": "https://www.acatlan.unam.mx/index.php?id=1297",
	"imagen": "cursos/E OCC.png"
}, {
	"id": "79",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "70",
	"curso": "Derecho corporativo",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-05-22",
	"link": "https://www.acatlan.unam.mx/index.php?id=1382",
	"imagen": "cursos/E DC.png"
}, {
	"id": "80",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "52",
	"curso": "Programación Neurolingüística y Desarrollo Humano",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-05-21",
	"link": "https://www.acatlan.unam.mx/index.php?id=1308",
	"imagen": "cursos/D PNL.png"
}, {
	"id": "81",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "56",
	"curso": "Negocios internacionales",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-05-21",
	"link": "https://www.acatlan.unam.mx/index.php?id=1308",
	"imagen": "cursos/E NI.png"
}, {
	"id": "84",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "116",
	"curso": "Derecho procesal civil y familiar",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-06-04",
	"link": "https://www.acatlan.unam.mx/index.php?id=1197",
	"imagen": "cursos/E ProcesalCivilF.png"
}, {
	"id": "86",
	"tipo": "Diplomado",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "34",
	"curso": "Amparo",
	"modalidad": "Semipresencial",
	"duracion": "240",
	"cuota": "16500.00",
	"fecha_inicio": "2022-05-28",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/3141",
	"imagen": "cursos/amparo.jpg"
}, {
	"id": "101",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "129",
	"curso": "Comercio exterior",
	"modalidad": "A distancia",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-06-25",
	"link": "https://www.acatlan.unam.mx/index.php?id=402",
	"imagen": "cursos/E CE.png"
}, {
	"id": "123",
	"tipo": "Diplomado",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "140",
	"curso": "Comunicación estratégica, política y social",
	"modalidad": "En línea",
	"duracion": "240",
	"cuota": "22560.00",
	"fecha_inicio": "2022-06-26",
	"link": "https://www.acatlan.unam.mx/index.php?id=1553",
	"imagen": "cursos/comunicación estratégica.jpg"
}, {
	"id": "34",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "81",
	"curso": "Inglés: Habilidades Comunicativas Negociación, Academia y Ventas ",
	"modalidad": "En línea",
	"duracion": "60",
	"cuota": "4500.00",
	"fecha_inicio": "2022-02-28",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/2331",
	"imagen": "cursos/habilidades.jpg"
}, {
	"id": "35",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "83",
	"curso": "Inglés: Taller de expresión oral y conversación en inglés niveles B1 y B2",
	"modalidad": "En línea",
	"duracion": "60",
	"cuota": "4500.00",
	"fecha_inicio": "2022-05-30",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/2623",
	"imagen": "cursos/ingles b1 be.jpg"
}, {
	"id": "36",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "82",
	"curso": "Inglés: Perfeccionamiento de Producción Oral y Producción Auditiva en 30 Días",
	"modalidad": "En línea",
	"duracion": "12",
	"cuota": "2500.00",
	"fecha_inicio": "2022-02-28",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/2344",
	"imagen": "cursos/perfecionamiento.jpg"
}, {
	"id": "39",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "Palacio de Autonomía",
	"id_curso": "79",
	"curso": "Inglés Jurídico",
	"modalidad": "En línea",
	"duracion": "80",
	"cuota": "6500.00",
	"fecha_inicio": "2022-04-25",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/funam/detalles/2905",
	"imagen": "cursos/inglés juridico.jpg"
}, {
	"id": "61",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "99",
	"curso": "Italiano comprensión de lectura B-learning",
	"modalidad": "Semipresencial",
	"duracion": "120",
	"cuota": "5700.00",
	"fecha_inicio": "2022-05-21",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/3130",
	"imagen": "cursos/italiano B-learning.jpg"
}, {
	"id": "63",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "100",
	"curso": "Inglés comprensión de lectura E-Learning",
	"modalidad": "En línea",
	"duracion": "180",
	"cuota": "5700.00",
	"fecha_inicio": "2022-06-04",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/3107",
	"imagen": "cursos/Ingles E-learning.jpg"
}, {
	"id": "92",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "75",
	"curso": "Comprensión de Lectura en Inglés",
	"modalidad": "Presencial",
	"duracion": "72",
	"cuota": "5200.00",
	"fecha_inicio": "2022-05-28",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/3126",
	"imagen": "cursos/Ingles Sab y dom.jpg"
}, {
	"id": "93",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "76",
	"curso": "Comprensión de Lectura en Italiano",
	"modalidad": "Presencial",
	"duracion": "120",
	"cuota": "3700.00",
	"fecha_inicio": "2022-05-28",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/3109",
	"imagen": "cursos/Italiano presencial.jpg"
}, {
	"id": "102",
	"tipo": "Idiomas",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "73",
	"curso": "Alemán, Plan Global - 1º nivel - 09 a 13 horas sabatino",
	"modalidad": "A distancia",
	"duracion": "48",
	"cuota": "3100.00",
	"fecha_inicio": "2022-02-19",
	"link": "https://facebook.com/sedescei",
	"imagen": "cursos/Alemán S.png"
}, {
	"id": "103",
	"tipo": "Idiomas",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "77",
	"curso": "Francés, Plan Global - Primer nivel",
	"modalidad": "A distancia",
	"duracion": "48",
	"cuota": "3500.00",
	"fecha_inicio": "2022-02-19",
	"link": "https://facebook.com/sedescei",
	"imagen": "cursos/Francés S.png"
}, {
	"id": "104",
	"tipo": "Idiomas",
	"entidad": "FES Acatlán",
	"sede": "CEIM Izcalli",
	"id_curso": "80",
	"curso": "Inglés, Plan Global - 1º nivel - 07 a 09 horas lunes a jueves",
	"modalidad": "A distancia",
	"duracion": "48",
	"cuota": "3100.00",
	"fecha_inicio": "2022-05-16",
	"link": "https://facebook.com/sedescei",
	"imagen": "cursos/Inglés I07.png"
}, {
	"id": "105",
	"tipo": "Idiomas",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "130",
	"curso": "Inglés, Plan Global - 1º nivel - 19 a 21 horas lunes a jueves",
	"modalidad": "A distancia",
	"duracion": "48",
	"cuota": "3100.00",
	"fecha_inicio": "2022-02-14",
	"link": "https://facebook.com/sedescei",
	"imagen": "cursos/Inglés I19.png"
}, {
	"id": "106",
	"tipo": "Idiomas",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "131",
	"curso": "Inglés, Plan Global - 1º nivel - 09 a 13 horas sabatino",
	"modalidad": "A distancia",
	"duracion": "48",
	"cuota": "3100.00",
	"fecha_inicio": "2022-02-19",
	"link": "https://facebook.com/sedescei",
	"imagen": "cursos/Inglés S.png"
}, {
	"id": "107",
	"tipo": "Idiomas",
	"entidad": "FES Acatlán",
	"sede": "Palacio de Autonomía",
	"id_curso": "85",
	"curso": "Japonés, Plan Global - 1º nivel - 09 a 13 horas dominical",
	"modalidad": "A distancia",
	"duracion": "48",
	"cuota": "3100.00",
	"fecha_inicio": "2022-02-20",
	"link": "https://facebook.com/sedescei",
	"imagen": "cursos/Japonés D.png"
}, {
	"id": "121",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "138",
	"curso": "Inglés comprensión de lectura B-Learning",
	"modalidad": "Semipresencial",
	"duracion": "180",
	"cuota": "5700.00",
	"fecha_inicio": "2022-05-22",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/3128",
	"imagen": "cursos/Inglés B-learning.jpg"
}, {
	"id": "122",
	"tipo": "Idiomas",
	"entidad": "FES Aragón",
	"sede": "CCAP Los Galeana",
	"id_curso": "139",
	"curso": "Inglés posesión (sábado) Nivel 1 al 6",
	"modalidad": "Presencial",
	"duracion": "360",
	"cuota": "16200.00",
	"fecha_inicio": "2022-05-21",
	"link": "https://cedco.aragon.unam.mx/sigedco/eventos/CEDCO/detalles/3120",
	"imagen": "cursos/ingles posesión sabatino.jpg"
}];

export default eventsData;
